language: python

python:
  - "2.7"

before_install:
  - git clone https://github.com/cknoll/rst_symbtools.git
  - python rst_symbtools/setup.py install

install:
 - python setup.py install
 - python -c "import pycartan"

# command to run tests
script:
 - python pycartan/tests/test_pycartan.py
