language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
 - pip install --upgrade pip
 - pip install sympy
 - pip install --upgrade sympy
 - pip install -r requirements.txt
 - pip install -e .

# command to run tests
script:
 - python -c "import sympy; print(sympy.__version__)"
 - python -c "import symbtools; print(symbtools.__version__)"
 - python pycartan/tests/test_pycartan.py
