language: python

python:
  - "2.7"

before_install:
 - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
# - chmod +x miniconda.sh
 - bash ./miniconda.sh -b
 - export PATH=/home/travis/miniconda2/bin:$PATH
 - export DEPS="sympy numpy pytest"
 - conda update --yes --no-deps conda
 - conda update --yes conda
  

install:
 - conda install --yes -c conda sympy numpy pytest
 - python -c "import sympy; print sympy.__version__"
#  - conda create -n testenv --yes $DEPS pip python=$TRAVIS_PYTHON_VERSION
#  - whereis activate
#  - python2 --version
#  - python2 -c "import sys; print '\\n'.join(sys.path)"
#  - python --version
#  - whereis activate
#  - source activate testenv
#  - python --version
#  - python2 --version
#  - python2 -c "import sys; print '\\n'.join(sys.path)"
#  - echo $DEPS
#  - echo $TRAVIS_PYTHON_VERSION
# 
#  - python -c "import sympy; print sympy.__version__"
 - git clone https://github.com/cknoll/rst_symbtools.git
 - cd rst_symbtools
 - python2 setup.py install
 - cd ..
 - python2 setup.py install

# command to run tests
script:
 - python2 pycartan/tests/test_pycartan.py
