language: python

python:
  - "2.7"
  - "3.4"

before_install:
 - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - bash ./miniconda.sh -b
 - export PATH=/home/travis/miniconda3/bin:$PATH
 - conda update --yes --no-deps conda
 - conda update --yes conda
  

install:
 - conda install --yes -c conda sympy numpy
 - python -c "import sympy; print(sympy.__version__)"
 - git clone https://github.com/TUD-RST/symbtools.git
 - cd symbtools
 - python setup.py install
 - cd ..
 - pip install -e .

# command to run tests
script:
 - python pycartan/tests/test_pycartan.py
